### ISSUE TITLE
Build job for PHP 7 on Travis CI fails even if there are no failures

### ISSUE THREAD

**Issue by mhujer** [zendframework/zf1#544]
There are no failures in the PHP 7 job, but it is still reported as failed *The command "php runalltests.php" exited with 139.*

I will have a look, what's wrong.

**Comment by akrabat** [comment]
139 is a segfault, I believe.

**Comment by mhujer** [comment]
Something is wrong with Zend/Db test - "Result of Zend/Db/AllTests.php is 139"

**Comment by mhujer** [comment]
By disabling and enabling tests, I was able to narrow it down to Pgsql tests (it does not segfault when they are disabled).

Testing branch: https://github.com/mhujer/zf1/tree/php7travis
Example build: https://travis-ci.org/mhujer/zf1/builds/57008989

I will leave the issue open, as it will be probably resolved in one of the next PHP7 nightly builds.
Or do you know anyone from the php devs itself who can help us to investigate the issue? (I assume that they are interested in segfault reports)

**Comment by froschdesign** [comment]
> I will leave the issue open…

:+1:

**Comment by PHPGangsta** [comment]
The build for PHP7 currently fails because of "Nesting level too deep" Fatal error in Zend/Paginator:
https://travis-ci.org/zendframework/zf1/jobs/62530663

Executing Zend/Paginator/AllTests.php
PHPUnit 3.7.38 by Sebastian Bergmann.
Configuration read from /home/travis/build/zendframework/zf1/tests/phpunit.xml
...............................................................  63 / 188 ( 33%)
............................................................... 126 / 188 ( 67%)
........PHP Fatal error:  Nesting level too deep - recursive dependency? in /home/travis/build/zendframework/zf1/tests/Zend/Paginator/Adapter/IteratorTest.php on line 127
Fatal error: Nesting level too deep - recursive dependency? in /home/travis/build/zendframework/zf1/tests/Zend/Paginator/Adapter/IteratorTest.php on line 127

Finished executing Zend/Paginator/AllTests.php
Result of Zend/Paginator/AllTests.php is 255

**Comment by mhujer** [comment]
It currently fails on (it does some debug_backtrace parsing, so it may be a BC break):
```
1) Zend_Log_Writer_FirebugTest::testFileLineOffsets
File and line does not match for message number: 2
/home/travis/build/mhujer/zf1/tests/Zend/Log/Writer/FirebugTest.php:342
FAILURES!
Tests: 127, Assertions: 235, Failures: 1, Skipped: 3.
```

But the original segfaulting issue resolved itself, so I'm closing this one.
