### ISSUE TITLE
Server error: The use statement with non-compound name 'Zend_View_Helper_FormElement' has no effect

### ISSUE THREAD

**Issue by lhorace** [zendframework/zf1#574]
Hello,

CentOS7
PHP5.6.9

I am reporting a bug against Zend Framework in regards to a IcingaWeb2 if a bug report hasn't been reported by Icinga folks. See below:

Server error: The use statement with non-compound name 'Zend_View_Helper_FormElement' has no effect

#0 /usr/share/icingaweb2/library/vendor/Zend/Loader/PluginLoader.php(397): Icinga\Application\ApplicationBootstrap->Icinga\Application{closure}(2, 'The use stateme...', '/usr/share/icin...', 4, Array)
#1 /usr/share/icingaweb2/library/vendor/Zend/Loader/PluginLoader.php(397): Zend_Loader_PluginLoader::load()
#2 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(1168): Zend_Loader_PluginLoader->load('FormNumber')
#3 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(610): Zend_View_Abstract->_getPlugin('helper', 'formNumber')
#4 /usr/share/icingaweb2/library/vendor/Zend/Form/Decorator/ViewHelper.php(240): Zend_View_Abstract->getHelper('formNumber')
#5 /usr/share/icingaweb2/library/vendor/Zend/Form/Element.php(2048): Zend_Form_Decorator_ViewHelper->render('')
#6 /usr/share/icingaweb2/library/vendor/Zend/Form/Decorator/FormElements.php(115): Zend_Form_Element->render()
#7 /usr/share/icingaweb2/library/vendor/Zend/Form.php(2974): Zend_Form_Decorator_FormElements->render('\n

**Comment by croensch** [comment]
ZF1 has no use statements, so by following the stack trace i found icinga2 [has them](https://github.com/Icinga/icingaweb2/search?utf8=%E2%9C%93&q=Zend_View_Helper_FormElement) especially [the one you encountered](https://github.com/Icinga/icingaweb2/blob/ea4de8254586a222a1f4282f826219bc8ffd100f/application/views/helpers/FormNumber.php). I guess it happens because it is the only use statement and that means one would not even have to write it there. I also think that this error comes up because the error level includes E_WARNING which this error is of.

**Comment by froschdesign** [comment]
Btw. It's a very bad idea to use the prefix `Zend` for own classes:

1. These are not official ZF classes.
2. It will create confusion for users.
