### ISSUE TITLE
Zend_View_Abstract::escape do not escape apostrophe.

### ISSUE THREAD

**Issue by kapilsharma** [zendframework/zf1#588]
In my project, I needed to escape a message containing apostrophe (') but it was not escaped by Zend_View_Abstract::escape()

Looking at code, I find `ENT_COMPAT` is hard-coded in escape(), and thus there is no way to change default behaviour.

Test https://github.com/kapilsharma/zf1/commit/675ae7fd06c41bbed61123d0db7b5d90c2291225 confirms that.

Solution for this is available at https://github.com/kapilsharma/zf1/commit/ebbc589dafc7545e4cdc433acdfaa291a2d4284c

**Comment by kapilsharma** [comment]
Whole change ready for pull request is https://github.com/zendframework/zf1/compare/master...kapilsharma:issue_view_escape

Test result after new test

```bash
sh runtests.sh Zend_View
+ ../bin/phpunit --verbose --group Zend_View AllTests
PHPUnit 3.7.38 by Sebastian Bergmann.

Configuration read from /home/kapil/dev/github/zendframework/zf1/tests/phpunit.xml

...........................................................    59 / 14542 (  0%)
...........................................................   118 / 14542 (  0%)
...........................................................   177 / 14542 (  1%)
...........................................................   236 / 14542 (  1%)
...........................................................   295 / 14542 (  2%)
...........................................................   354 / 14542 (  2%)
...........................................................   413 / 14542 (  2%)
...........................................................   472 / 14542 (  3%)
...........................................................   531 / 14542 (  3%)
...........................................................   590 / 14542 (  4%)
...........................................................   649 / 14542 (  4%)
S..........................................................   708 / 14542 (  4%)
...........................................................   767 / 14542 (  5%)
....

Time: 7.76 seconds, Memory: 256.75Mb

There was 1 skipped test:

1) Zend_View_Helper_Navigation_SitemapTest::testUseSchemaValidation
Skipped because it fetches XSD from web

/home/kapil/dev/github/zendframework/zf1/tests/Zend/View/Helper/Navigation/SitemapTest.php:283
OK, but incomplete or skipped tests!
Tests: 771, Assertions: 1677, Skipped: 1.
```

**Comment by kapilsharma** [comment]
Created a pull request #589

**Comment by froschdesign** [comment]
> In my project, I needed to escape a message containing apostrophe (') but it was not escaped by Zend_View_Abstract::escape()

[You can use the `setEscape()` method.](http://framework.zend.com/manual/1.12/en/zend.view.scripts.html#zend.view.scripts.escaping)

**Comment by kapilsharma** [comment]
Yes we can set but I needed `htmlspecialchars` as escape method, which is default so `setEscape` will not work. Writing custom function for such simple thing is not good. Right now we used PHP's native [htmlspecialchars](http://php.net/manual/en/function.htmlspecialchars.php) as special case, which make code incosistent.

Problem is not setting escape method but hard-coded $flags (second parameter) of [htmlspecialchars](http://php.net/manual/en/function.htmlspecialchars.php)

**Comment by froschdesign** [comment]
> Writing custom function for such simple thing is not good.

Why? It's your own use case to escape the apostrophe. The standard escape method from `Zend_View` helps to avoid cross-site scripting attacks – not more and not less.

> Problem is not setting escape method but hard-coded $flags (second parameter) of htmlspecialchars

The problem is: we are on the road to version 3 of the Zend Framework and adding new features to version 1 is the wrong direction. See the Contributor Guide (ZF v1):

> For ZF1, we are accepting bug fixes to existing components.

http://framework.zend.com/participate/contributor-guide-v1

**Comment by akrabat** [comment]
I think this will work for you:

```php
$view->setEscape(function($var) { 
    return htmlspecialchars($var, ENT_QUOTES, $view->getEncoding()); 
});
```

**Comment by DragonBe** [comment]
@akrabat so for each time we need to escape quoted strings, we need to pass in this callback function, which is not really allowing us to configure once and reuse.

@froschdesign I agree with the only bugfixes decision, but this is IMO a bug and not a feature as we're not able to escape quoted strings in our presentation view.

If you want I can send you all the various use cases and test cases to prove this. It was me that advised @kapilsharma to report it as a bug in the first place.

**Comment by froschdesign** [comment]
@DragonBe 
> so for each time we need to escape quoted strings, we need to pass in this callback function, which is not really allowing us to configure once and reuse.

Each time? No! You can use the `Zend_Application` with a bootstrap class.

> but this is IMO a bug and not a feature as we're not able to escape quoted strings in our presentation view.

That's not true, because you are able to escape quoted strings – see `setEscape()`.
This is the documented behavior:

> One of the most important tasks to perform in a view script is to make sure that output is escaped properly; among other things, this helps to avoid cross-site scripting attacks.
…
By default, the escape() method uses the PHP htmlspecialchars() function for escaping. However, depending on your environment, you may wish for escaping to occur in a different way. Use the setEscape() method at the controller level to tell Zend_View what escaping callback to use.

http://framework.zend.com/manual/1.12/en/zend.view.scripts.html#zend.view.scripts.escaping

> If you want I can send you all the various use cases and test cases to prove this. It was me that advised @kapilsharma to report it as a bug in the first place.

If you can provide a cross-site scripting attack only with an unquoted string, then we can mark this issue as a bug report. :wink:

(Don't get me wrong, I can see the use case, but this ends up always in a feature request.)

**Comment by akrabat** [comment]
I'm not intrinsically against the PR, but for an addition, there has to be a clear and unambiguous benefit to the project for adding it.

In this case, I think we probably need to consider doing some work around `escape()` because looking at ZF2's `Zend\Escaper`, I see that it uses ENT_QUOTES and adds ENT_SUBSTITUTE if PHP 5.4 or higher is in use. These changes presumably were made for a reason.

I suspect that we can't just change our defaults though…

**Comment by froschdesign** [comment]
I will close this issue report, because:

- since version 0.6.0 (released 2006-12-16) `ENT_COMPAT` is hard-coded
- since version 0.1.3 or earlier (released 2006-04-18 and earlier) a different escaping function can be set
- since version 1.8.0 (released 2009-04-30) it is easy to set a different escaping function in one place ("globally") – `Zend_Application`
- since PHP 5.3 it is very easy to set a different escaping function
- it is a feature request and not a bug report

**Comment by DragonBe** [comment]
@akrabat + @froschdesign: thanks for your feedback. Even though I don't fully agree with the arguments presented I do see the vision behind it.

We will sort it out locally and implement it as you said with `setEscape()` to provide the security on our web application.

**Comment by froschdesign** [comment]
@DragonBe 
> I do see the vision behind it

Thanks!
