### ISSUE TITLE
Wrong return type in DocBlock of Zend_Console_Getopt::getOption()

### ISSUE THREAD

**Issue by Whissi** [zendframework/zf1#599]
Hi,

```php
$options = new \Zend_Console_Getopt(
	array(
		'test|t=i' => 'Test option with required integer value'
	)
);

$options->parse();


if ($options->getOption('test') !== FALSE) {
	printf("'test' option with value '%s' was given!", $options->getOption('start'));
}
else {
	echo "'test' option was omitted!";
}
```
When you call the code above from CLI like `php test.php` (I don't **set** the *test* option!) [I would expect](https://github.com/zendframework/zf1/blob/master/library/Zend/Console/Getopt.php#L553) to get the output
```
'test' option was omitted!
```
but I will get
```
'test' option with value '' was given!
```

Tested with ZF 1.12.14.

**Comment by froschdesign** [comment]
Let's look at the reference guide:
> Fetching Options by Name
You can use the getOption() method to query the value of an option. If the option had a parameter, this method returns the value of the parameter. If the option had no parameter but the user did specify it on the command-line, the method returns TRUE. **Otherwise the method returns NULL.**

http://framework.zend.com/manual/1.12/en/zend.console.getopt.fetching.html#zend.console.getopt.fetching.byname

If we change the type of the return value, then it would be a BC break.

Solution: Update the DocBlock
