### ISSUE TITLE
Routes defined with Zend_Config_Ini:  Zend_Navigation does not find active page (ZF1.12.16 & PHP5.4)

### ISSUE THREAD

**Issue by Nicolasix** [zendframework/zf1#629]
I've got this route defined within an ini file:
```
resources.router.routes.cv.route = ":user/cv/:action/:object/:id"
resources.router.routes.cv.defaults.module = cv
resources.router.routes.cv.defaults.controller = cv
resources.router.routes.cv.defaults.action = index
resources.router.routes.cv.defaults.user = my
resources.router.routes.cv.defaults.object = null
resources.router.routes.cv.defaults.id = null
resources.router.routes.cv.reqs.object ="(job|degree|training)"
```
"id" and "object" are set to null since they are optional.

Zend_Config_Ini  `_parseIniFile()` method convert null value to empty string.
As a result Zend_Navigation_Page_Mvc `isActive()` method fails to find active page:
```
...
foreach ($myParams as $key => $value) {
    if (null === $value) { // <--------------------- false in my context
        unset($myParams[$key]);
    }
}

if (count(array_intersect_assoc($reqParams, $myParams)) ==
    count($myParams)
) {  // <----------------------------------------- false in my context
    $this->_active = true;
    return true;
}
...
```

**Comment by froschdesign** [comment]
`null` is not handled by `Zend_Config_Ini`, because of `parse_ini_file`. Please look at the docs:

> Note: Parsing the INI File
Zend_Config_Ini utilizes the » parse_ini_file() PHP function. Please review this documentation to be aware of its specific behaviors, which propagate to Zend_Config_Ini, such as how the special values of "TRUE", "FALSE", "yes", "no", and "NULL" are handled. 

http://framework.zend.com/manual/1.12/en/zend.config.adapters.ini.html

If you use PHP 5.6.1 or higher, then you can extend `Zend_Config_Ini` and add the `scanner_mode`. See: http://php.net/manual/en/function.parse-ini-file.php
