### ISSUE TITLE
Don't EOL

### ISSUE THREAD

**Issue by biji** [zendframework/zf1#715]
Keep maintaining zend framework 1 please. until ZF3 mature

**Comment by Jimbolino** [comment]
There is also no clear migration guide available:
https://framework.zend.com/manual/2.4/en/migration/overview.html

for example Zend_Db and Zend_Config are not compatible with Zend\Db and Zend\Config
and for Zend_Registry. there is no alternative...

**Comment by adamlundrigan** [comment]
Volunteer time is scarce and community involvement in maintaining ZF1 has long since tailed off.  ZF1's days were numbered the day ZF2 went stable.  At that time (and many times since) the ZF team has signalled [a timeline of 18-24 months](https://framework.zend.com/blog/zend-framework-2-0-0-stable-released.html) for supporting both versions; when ZF1 actually hits EOL on 28 September it will have been just over 48 months since ZF2's release. 

If you're looking for assistance upgrading your ZF1 application you really only have two choices at this point:

 1. Google "ZF1 to ZF2 migration" and read everything you find there.  PHP Architect [also sells a book](https://www.phparch.com/books/zend-framework-migration-guide/) on the subject written by a well-known Zend Framework contributor.  Definitely upgrade to ZF3 components wherever possible.

 2. Contact Zend's professional services group, they'll surely help you out for a fee (see [the ZF1 EOL announcement](https://framework.zend.com/blog/2016-06-28-zf1-eol.html) for more on that)

While some ZF2 components have directly-compatible ZF1 counterparts, many do not.  The MVC system is completely different between ZF1 and ZF2.  ZF2 has a whole dependency injection / IoC package that ZF1 does not.  Unfortunately these changes do not allow for a single, simple upgrade path as the degree of work required to migrate your application from ZF1 to ZF2 depends on how tightly coupled it is to the parts which changed significantly (MVC & DB, mainly). 

As I said off the top...volunteer resources are scarce and maintaining a framework which was superseded four years ago isn't a viable option.  I don't speak for the ZF team, but their decision to EOL ZF1 says exactly that to me.
